### ISSUE TITLE
Add node 14 base

### ISSUE THREAD

**Issue by godber** [terascope/base-docker-image#1]
I would have tried using this base image here:

https://github.com/terascope/teraslice-exporter/blob/v0.1.0/Dockerfile#L1

But there was no node14 build (or maybe there was in docker hub and I shouldn't have believed the readme).  I am happy with how my image came out, so I don't really need this, but if adding node 14 isn't a big deal, I'd try to use it in the future.

**Comment by peterdemartini** [comment]
It doesn't appear that node-rdkafka supports node 14 yet so we are blocked by that

**Comment by godber** [comment]
This is clearly out of date since we have a node14 base.
