### ISSUE TITLE
Adding node 22 base image

### ISSUE THREAD

**Issue by sotojn** [terascope/base-docker-image#24]
We need to add node 22 to the base image so we can start testing it in teraslice. To achieve this we need to update the following arrays:

https://github.com/terascope/base-docker-image/blob/44e5be0d3b965ee2f1118b4b1f32f5c2afc6dbd1/.github/workflows/build.yml#L15
https://github.com/terascope/base-docker-image/blob/44e5be0d3b965ee2f1118b4b1f32f5c2afc6dbd1/.github/workflows/release.yml#L16

Adding node `22.1.0` to this will create images to docker hub that teraslice can use.

**Comment by godber** [comment]
There is now a Node `22.2.0` release: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.2.0
