### ISSUE TITLE
Move Image from Docker Hub to GHCR

### ISSUE THREAD

**Issue by godber** [terascope/base-docker-image#32]
Currently these images are published to docker hub, lets move them to the GitHub container registry.

Make sure we use Container Registry NOT Docker Registry:

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

When this is done, we will want to change the Teraslice Dockerfile to use the new location and then file a similar issue in Teraslice to move that image.

**Comment by sotojn** [comment]
This has been resolved with the following two PR's

Teraslice PR:
https://github.com/terascope/teraslice/pull/3699

Base image PR:
https://github.com/terascope/base-docker-image/pull/34
